# HINWEIS: Dies ist die finale, Dockerfile-basierte Konfiguration.

app = 'wasserqualitaet-vg-bitter-frost-7826'
primary_region = 'fra'

# Der [build]-Abschnitt wird komplett entfernt.
# Fly.io erkennt das Dockerfile automatisch.

[env]
  PORT = "8080"

[mounts]
  source = "mailer_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "npm start"

[[cron]]
  schedule = "0 5 * * *"
  command = "node send-digest.js"