# HINWEIS: Dies ist die finale, korrigierte Version der fly.toml,
# die die Build-Prozesse für Node.js und Python explizit und korrekt definiert.

app = 'wasserqualitaet-vg-bitter-frost-7826'
primary_region = 'fra'

[build]
  # Wir geben dem Builder eine explizite Liste der benötigten Sprach-Pakete.
  # Dies ist die robusteste Methode.
  buildpacks = ["heroku/nodejs", "heroku/python"]

[env]
  PORT = "8080"

[mounts]
  source = "mailer_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "npm start"

[[cron]]
  schedule = "0 5 * * *"
  command = "node send-digest.js"