# Finale, korrigierte Konfiguration für die Backend-Anwendung

app = 'wasserqualitaet-vg-bitter-frost-7826'
primary_region = 'fra'

[build]
  # KORREKTUR: Wir verwenden einen weit verbreiteten und aktuellen Standard-Builder
  builder = "heroku/builder:22"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "npm start"

[[cron]]
  schedule = "0 5 * * *"
  command = "node send-digest.js"