# Finale, vollständige Konfiguration für die Backend-Anwendung

app = 'wasserqualitaet-vg-bitter-frost-7826'
primary_region = 'fra'

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "8080"

# NEU & ENTSCHEIDEND: Definiert, wie persistente Volumes eingebunden werden
[mounts]
  source = "app_data" # Der Name des Volumes auf Fly.io
  destination = "/data" # Der Pfad innerhalb des Containers, wo die Daten gespeichert werden sollen

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "npm start"

[[cron]]
  schedule = "0 5 * * *"
  command = "node send-digest.js"