# HINWEIS: Dies ist die finale, korrekte Konfiguration für Ihr Backend,
# die explizit die Build-Prozesse für Node.js und Python definiert.

app = 'wasserqualitaet-vg-bitter-frost-7826'
primary_region = 'fra'

[build]
  # Wir sagen dem Builder explizit, welche Sprach-Pakete er verwenden soll.
  # Dies ist die robusteste Methode für Projekte mit mehreren Sprachen.
  [[build.buildpacks]]
    uri = "heroku/nodejs"
  [[build.buildpacks]]
    uri = "heroku/python"

[env]
  PORT = "8080"

[mounts]
  source = "mailer_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "npm start"

[[cron]]
  schedule = "0 5 * * *"
  command = "node send-digest.js"