# Finale, explizite Konfiguration für die Backend-Anwendung

app = 'wasserqualitaet-vg-bitter-frost-7826'
primary_region = 'fra'

# NEU & ENTSCHEIDEND: Explizite Anweisung an Fly.io, den Node.js Buildpack zu verwenden
[build]
  builder = "flyio/buildpack-node"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  # Verwendet das "start"-Skript aus der package.json
  app = "npm start"

[[cron]]
  # Führt den Task jeden Tag um 05:00 Uhr UTC (07:00 Uhr deutsche Sommerzeit) aus
  schedule = "0 5 * * *"
  command = "node send-digest.js"