# Konfiguration f端r die Backend-Anwendung auf Fly.io

app = 'wasserqualitaet-vg-bitter-frost-7826' # Ihr App-Name
primary_region = 'fra'

# Definiert den Build-Befehl, der vor dem Start ausgef端hrt wird
[build]
  command = "npm install"

# Definiert den Hauptprozess, der auf HTTP-Anfragen lauscht
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"] # Wichtig: Nur der "app"-Prozess ist ein Web-Service

# Ordnet den Prozess-Namen die Startbefehle zu
[processes]
  app = "node server.js"
  # 'send-digest' wird hier entfernt, da es kein dauerhafter Prozess ist

# NEU: Definiert geplante Tasks (Cronjobs)
[[cron]]
  # F端hrt den Task jeden Tag um 05:00 Uhr UTC (07:00 Uhr deutsche Sommerzeit) aus
  schedule = "0 5 * * *" 
  command = "node send-digest.js"
  
# Umgebungsvariablen f端r den Web-Server
[env]
  PORT = "8080"